version: "3.7"
services:
  frontend:
    container_name: Frontend_KR
    build:
      context: ./Frontend
    ports: 
      - "3008:3008" # Porta do frontend
    networks:
      - app-network 
networks:
  app-network:
    driver: bridge